//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public int Id { get; set; }
        public int srcCurrencyId { get; set; }
        public int trgtCurrencyId { get; set; }
        public double rate { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
